CREATE TABLE IF NOT EXISTS libros (
    id_libro SERIAL PRIMARY KEY,
    codigo INTEGER UNIQUE NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    ejemplares_sede1 INTEGER DEFAULT 0,
    ejemplares_sede2 INTEGER DEFAULT 0,
    ejemplares_totales_sede1 INTEGER DEFAULT 0,
    ejemplares_totales_sede2 INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS estados (
    id_estado SERIAL PRIMARY KEY,
    id_libro INTEGER REFERENCES libros(id_libro),
    tipo_operacion VARCHAR(50) NOT NULL,
    fecha_operacion TIMESTAMP DEFAULT NOW(),
    fecha_devolucion_prevista DATE,
    sede INTEGER NOT NULL,
    renovaciones INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS operation_log (
    id SERIAL PRIMARY KEY,
    request_type INT NOT NULL,
    code INT NOT NULL,
    location INT NOT NULL,
    timestamp TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_operation_log_timestamp ON operation_log(timestamp);

INSERT INTO libros (codigo, titulo, autor, ejemplares_sede1, ejemplares_sede2, ejemplares_totales_sede1, ejemplares_totales_sede2) VALUES
(100001, 'Cien Años de Soledad', 'Gabriel García Márquez', 3, 4, 5, 5),
(100002, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 5, 3, 6, 6),
(100003, 'El Amor en los Tiempos del Cólera', 'Gabriel García Márquez', 2, 5, 4, 5),
(100004, 'La Sombra del Viento', 'Carlos Ruiz Zafón', 4, 2, 5, 5),
(100005, 'Crónica de una Muerte Anunciada', 'Gabriel García Márquez', 3, 3, 4, 4),
(100006, 'Rayuela', 'Julio Cortázar', 5, 4, 5, 6),
(100007, 'Pedro Páramo', 'Juan Rulfo', 2, 3, 3, 4),
(100008, 'La Casa de los Espíritus', 'Isabel Allende', 4, 5, 6, 5),
(100009, 'El Túnel', 'Ernesto Sábato', 3, 2, 5, 5),
(100010, 'Ficciones', 'Jorge Luis Borges', 5, 5, 5, 5),
(100011, 'El Aleph', 'Jorge Luis Borges', 2, 4, 4, 4),
(100012, 'La Ciudad y los Perros', 'Mario Vargas Llosa', 3, 3, 5, 6),
(100013, 'Los Detectives Salvajes', 'Roberto Bolaño', 4, 2, 6, 5),
(100014, 'Aura', 'Carlos Fuentes', 5, 4, 5, 6),
(100015, 'El Llano en Llamas', 'Juan Rulfo', 2, 5, 3, 5),
(100016, 'Como Agua para Chocolate', 'Laura Esquivel', 3, 3, 5, 4),
(100017, 'La Tregua', 'Mario Benedetti', 4, 4, 4, 4),
(100018, 'El Otoño del Patriarca', 'Gabriel García Márquez', 5, 2, 6, 5),
(100019, 'Pantaleón y las Visitadoras', 'Mario Vargas Llosa', 3, 5, 5, 5),
(100020, 'Santa Evita', 'Tomás Eloy Martínez', 2, 3, 4, 6);

INSERT INTO estados (id_libro, tipo_operacion, fecha_operacion, fecha_devolucion_prevista, sede, renovaciones) VALUES
(1, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 1, 0),
(1, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 1, 0),
(2, 'prestamo', NOW() - INTERVAL '10 days', (NOW() + INTERVAL '4 days')::date, 1, 1),
(3, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 1, 0),
(3, 'prestamo', NOW() - INTERVAL '7 days', (NOW() + INTERVAL '7 days')::date, 1, 0),
(5, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 1, 0),
(7, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 1, 0),
(8, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 1, 0),
(8, 'prestamo', NOW() - INTERVAL '8 days', (NOW() + INTERVAL '6 days')::date, 1, 0),
(9, 'prestamo', NOW() - INTERVAL '9 days', (NOW() + INTERVAL '5 days')::date, 1, 1),
(9, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 1, 0),
(11, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 1, 0),
(11, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 1, 0),
(12, 'prestamo', NOW() - INTERVAL '7 days', (NOW() + INTERVAL '7 days')::date, 1, 0),
(12, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 1, 0),
(13, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 1, 0),
(13, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 1, 0),
(16, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 1, 0),
(16, 'prestamo', NOW() - INTERVAL '8 days', (NOW() + INTERVAL '6 days')::date, 1, 0),
(18, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 1, 0),
(20, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 1, 0),
(20, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 1, 0),
(1, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 2, 0),
(2, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 2, 0),
(2, 'prestamo', NOW() - INTERVAL '9 days', (NOW() + INTERVAL '5 days')::date, 2, 1),
(2, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 2, 0),
(3, 'devuelto', NOW() - INTERVAL '15 days', NULL, 2, 0),
(4, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 2, 0),
(4, 'prestamo', NOW() - INTERVAL '7 days', (NOW() + INTERVAL '7 days')::date, 2, 0),
(4, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 2, 0),
(6, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 2, 0),
(6, 'prestamo', NOW() - INTERVAL '8 days', (NOW() + INTERVAL '6 days')::date, 2, 0),
(7, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 2, 0),
(8, 'devuelto', NOW() - INTERVAL '20 days', NULL, 2, 0),
(9, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 2, 0),
(9, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 2, 0),
(9, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 2, 0),
(11, 'devuelto', NOW() - INTERVAL '12 days', NULL, 2, 0),
(12, 'prestamo', NOW() - INTERVAL '7 days', (NOW() + INTERVAL '7 days')::date, 2, 0),
(12, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 2, 0),
(12, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 2, 0),
(13, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 2, 0),
(13, 'prestamo', NOW() - INTERVAL '8 days', (NOW() + INTERVAL '6 days')::date, 2, 0),
(13, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 2, 0),
(14, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 2, 0),
(14, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 2, 0),
(16, 'prestamo', NOW() - INTERVAL '2 days', (NOW() + INTERVAL '12 days')::date, 2, 0),
(18, 'prestamo', NOW() - INTERVAL '5 days', (NOW() + INTERVAL '9 days')::date, 2, 0),
(18, 'prestamo', NOW() - INTERVAL '7 days', (NOW() + INTERVAL '7 days')::date, 2, 0),
(18, 'prestamo', NOW() - INTERVAL '3 days', (NOW() + INTERVAL '11 days')::date, 2, 0),
(20, 'prestamo', NOW() - INTERVAL '4 days', (NOW() + INTERVAL '10 days')::date, 2, 0),
(20, 'prestamo', NOW() - INTERVAL '1 day', (NOW() + INTERVAL '13 days')::date, 2, 0),
(20, 'prestamo', NOW() - INTERVAL '6 days', (NOW() + INTERVAL '8 days')::date, 2, 0);